---
- name: gather required facts
  setup:
    gather_subset: [hardware]
  when: ansible_memtotal_mb is not defined or ansible_processor_cores is not defined

- include_tasks: prepare.yml

- include_tasks: install.yml

- include_tasks: wsrep_notify.yml
  when: percona_cluster_wsrep_notify.enabled

- include_tasks: configure.yml
