---

- name: add percona repo
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb

- name: set root password
  debconf:
    name: "percona-xtradb-cluster-{{ percona_cluster_version|replace('.','') }}"
    question: "{{ item }}"
    value: "{{ percona_cluster_root_password }}"
    vtype: 'password'
  changed_when: false
  with_items:
    - 'root_password'
    - 'root_password_again'

- name: set root password again
  debconf:
    name: "percona-xtradb-cluster-server-{{ percona_cluster_version }}"
    question: "percona-xtradb-cluster-server/{{ item }}"
    value: "{{ percona_cluster_root_password }}"
    vtype: 'password'
  changed_when: false
  with_items:
    - 'root_password'
    - 'root_password_again'

- include_role:
    name: syslog
  vars:
    install_server: true
    default_server: rsyslog
  when: syslog_installed is not defined
